config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\Router;

Router::extensions(['pdf']);

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function ($routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Privilege.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Privilege Entity.
 *
 * @property int $id
 * @property string $name
 * @property int $is_only_brother
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 */
class Privilege extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Entity/PrivilegeType.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * PrivilegeType Entity.
 *
 * @property int $id
 * @property string $name
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 */
class PrivilegeType extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/PrivilegesTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Privilege;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Privileges Model
 *
 */
class PrivilegesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('privileges');
        $this->displayField('name');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('PrivilegeType', ['className' => 'PrivilegeTypes']);
        
        $this->belongsToMany('Individuals', [
            'foreignKey' => 'privilege_id',
            'targetForeignKey' => 'individual_id',
            'joinTable' => 'individuals_privileges'
        ]);
        
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->add('id', 'valid', ['rule' => 'numeric'])
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('name');

        return $validator;
    }
}

src/Controller/PrivilegesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Privileges Controller
 *
 * @property \App\Model\Table\PrivilegesTable $Privileges
 */
class PrivilegesController extends AppController
{

    
	public function isAuthorized($user)
	{
		
		if($this->request->action === 'index') {
			return true;
		}
		
		if($this->request->action === 'add') {
			return true;
		}
		
		if($this->request->action === 'edit') {
			return true;
		}
		
		return parent::isAuthorized($user);
	}
	
		        
    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        
        $this->paginate = [
            'contain' => ['PrivilegeType']
        ];
        
        $this->set('privileges', $this->paginate($this->Privileges));
        $this->set('_serialize', ['privileges']);
    }

    /**
     * View method
     *
     * @param string|null $id Privilege id.
     * @return void
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function view($id = null)
    {
        $privilege = $this->Privileges->get($id, [
            'contain' => []
        ]);
        $this->set('privilege', $privilege);
        $this->set('_serialize', ['privilege']);
    }

    /**
     * Add method
     *
     * @return void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $privilege = $this->Privileges->newEntity();
        if ($this->request->is('post')) {
            $privilege = $this->Privileges->patchEntity($privilege, $this->request->data);
            if ($this->Privileges->save($privilege)) {
                $this->Flash->success(__('The privilege has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The privilege could not be saved. Please, try again.'));
            }
        }
        $privilegeTypes = $this->Privileges->PrivilegeType->find('list');
        $this->set(compact('privilege', 'privilegeTypes'));
        $this->set('_serialize', ['privilege']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Privilege id.
     * @return void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $privilege = $this->Privileges->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $privilege = $this->Privileges->patchEntity($privilege, $this->request->data);
            if ($this->Privileges->save($privilege)) {
                $this->Flash->success(__('The privilege has been saved.'));
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The privilege could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('privilege'));
        $this->set('_serialize', ['privilege']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Privilege id.
     * @return void Redirects to index.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $privilege = $this->Privileges->get($id);
        if ($this->Privileges->delete($privilege)) {
            $this->Flash->success(__('The privilege has been deleted.'));
        } else {
            $this->Flash->error(__('The privilege could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Privileges/add.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Privileges'), ['action' => 'index']) ?></li>
    </ul>
</nav>
<div class="privileges form large-9 medium-8 columns content">
    <?= $this->Form->create($privilege) ?>
    <fieldset>
        <legend><?= __('Add Privilege') ?></legend>
        <?php
            echo $this->Form->input('privilege_type_id');
            echo $this->Form->input('name');
            echo $this->Form->input('is_sister', ['options' => [0 => 'No', 1 => 'Yes']]);
            echo $this->Form->input('is_brother', ['options' => [0 => 'No', 1 => 'Yes']]);
            echo $this->Form->input('is_qms', ['options' => [0 => 'No', 1 => 'Yes']]);
            echo $this->Form->input('is_elder', ['options' => [0 => 'No', 1 => 'Yes']]);
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Privileges/edit.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $privilege->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $privilege->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Privileges'), ['action' => 'index']) ?></li>
    </ul>
</nav>
<div class="privileges form large-9 medium-8 columns content">
    <?= $this->Form->create($privilege) ?>
    <fieldset>
        <legend><?= __('Edit Privilege') ?></legend>
        <?php
            echo $this->Form->input('name');
            echo $this->Form->input('is_brother');
            echo $this->Form->input('is_qms');
            echo $this->Form->input('is_elder');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Privileges/index.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Privilege'), ['action' => 'add']) ?></li>
    </ul>
</nav>
<div class="privileges index large-9 medium-8 columns content">
    <h3><?= __('Privileges') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th><?= $this->Paginator->sort('id') ?></th>
                <th><?= $this->Paginator->sort('name') ?></th>
                <th><?= $this->Paginator->sort('privilege_type_id') ?></th>
                <th><?= $this->Paginator->sort('is_sister', 'S') ?></th>
                <th><?= $this->Paginator->sort('is_brother', 'B') ?></th>
                <th><?= $this->Paginator->sort('is_qms', 'MS') ?></th>
                <th><?= $this->Paginator->sort('is_elder', 'E') ?></th>
                <th><?= $this->Paginator->sort('created') ?></th>
                <th><?= $this->Paginator->sort('modified') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($privileges as $privilege): ?>
            <tr>
                <td><?= $this->Number->format($privilege->id) ?></td>
                <td><?= h($privilege->name) ?></td>
                <td><?= h($privilege->privilege_type->name) ?></td>
                <td><?= $this->Number->format($privilege->is_sister) ?></td>
                <td><?= $this->Number->format($privilege->is_brother) ?></td>
                <td><?= $this->Number->format($privilege->is_qms) ?></td>
                <td><?= $this->Number->format($privilege->is_elder) ?></td>
                <td><?= h($privilege->created) ?></td>
                <td><?= h($privilege->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $privilege->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $privilege->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $privilege->id], ['confirm' => __('Are you sure you want to delete # {0}?', $privilege->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>

src/Template/Privileges/view.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Privilege'), ['action' => 'edit', $privilege->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Privilege'), ['action' => 'delete', $privilege->id], ['confirm' => __('Are you sure you want to delete # {0}?', $privilege->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Privileges'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Privilege'), ['action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="privileges view large-9 medium-8 columns content">
    <h3><?= h($privilege->name) ?></h3>
    <table class="vertical-table">
        <tr>
            <th><?= __('Name') ?></th>
            <td><?= h($privilege->name) ?></td>
        </tr>
        <tr>
            <th><?= __('Id') ?></th>
            <td><?= $this->Number->format($privilege->id) ?></td>
        </tr>
        <tr>
            <th><?= __('Is Brother') ?></th>
            <td><?= $this->Number->format($privilege->is_brother) ?></td>
        </tr>
        <tr>
            <th><?= __('Is Qms') ?></th>
            <td><?= $this->Number->format($privilege->is_qms) ?></td>
        </tr>
        <tr>
            <th><?= __('Is Elder') ?></th>
            <td><?= $this->Number->format($privilege->is_elder) ?></td>
        </tr>
        <tr>
            <th><?= __('Created') ?></th>
            <td><?= h($privilege->created) ?></tr>
        </tr>
        <tr>
            <th><?= __('Modified') ?></th>
            <td><?= h($privilege->modified) ?></tr>
        </tr>
    </table>
</div>